Provers implementation
ergoplatform/ergo-wallet pull request #4
Opened 2019-04-12 11:40 UTC by oskin1

2019-04-13 15:12 UTC, oskin1 commented
Third task from #1

2019-04-14 07:10 UTC, oskin1 commented
Relies on #3

2019-04-16 11:30 UTC, catena2w requested changes

2019-04-16 11:30 UTC, catena2w commented on src/main/scala/org/ergoplatform/wallet/interpreter/ErgoInterpreter.scala
> +  override def verify(env: ScriptEnv,
Please add comments describing parameters

2019-04-16 11:30 UTC, catena2w commented on src/main/scala/org/ergoplatform/wallet/interpreter/ErgoProvingInterpreter.scala
> +           stateContext: ErgoLikeStateContext): Try[ErgoLikeTransactionTemplate[Input]] = {
The result should be Try[ErgoLikeTransaction]

2019-04-16 11:30 UTC, catena2w commented on src/main/scala/org/ergoplatform/wallet/protocol/context/ErgoContext.scala
> +class ErgoContext(val stateContext: ErgoLikeStateContext,
Please add class comments

2019-04-16 11:30 UTC, catena2w commented on src/main/scala/org/ergoplatform/wallet/protocol/context/ErgoContext.scala
> +class ErgoContext(val stateContext: ErgoLikeStateContext,
Is it possible to simplify this class to reduce the number of classes with context? Do we really need to distinct `ErgoLikeStateContext` and `TransactionContext`? Or maybe we don't even need `ErgoContext` class here and can use ErgoLikeContext from sigma?

2019-04-16 16:29 UTC, catena2w approved these changes

2019-04-17 08:33 UTC, merged